services:
  # Domain A: Source Domain (domainA.local)
  samba-ad-a:
    image: smblds/smblds:latest
    container_name: fake_ad_domain_a
    platform: linux/amd64
    restart: unless-stopped
    environment:
      INSECURE_LDAP: "true"
      REALM: "DOMAINA.LOCAL"       # Becomes DC=domainA,DC=local
      DOMAIN: "DOMAINA"             # NetBIOS short name
      ADMINPASS: "SecretA123!"     # Password for CN=Administrator
    ports:
      - "389:389"   # Standard LDAP (Maps to DOMAIN_A_SERVER)
      - "636:636"   # LDAPS
    volumes:
      - ./entrypoint_a.d:/entrypoint.d
      - ./dev-certs:/certs  # <-- Point this to your project subfolder with the certs for DOMAIN_A_SERVER

  # Domain B: Target Domain (samdom.example.com)
  samba-ad-b:
    image: smblds/smblds:latest
    container_name: fake_ad_domain_b
    platform: linux/amd64
    restart: unless-stopped
    environment:
      INSECURE_LDAP: "true"
      REALM: "SAMDOM.EXAMPLE.COM"  # Becomes DC=samdom,DC=example,DC=com
      DOMAIN: "SAMDOM"              # NetBIOS short name
      ADMINPASS: "SecretB123!"     # Password for CN=Administrator
    ports:
      - "3389:389"  # Standard LDAP (Maps to DOMAIN_B_SERVER)
      - "3636:636"  # LDAPS
    volumes:
      - ./entrypoint_b.d:/entrypoint.d
      - ./dev-certs:/certs  # <-- Point this to your project subfolder with the certs for DOMAIN_B_SERVER
  
  # ==========================================
  # Domain C: External Test Domain (test.forest.net)
  # ==========================================
  samba-ad-c:
    image: smblds/smblds:latest
    container_name: fake_ad_domain_c
    platform: linux/amd64
    restart: unless-stopped
    environment:
      INSECURE_LDAP: "true"
      REALM: "TEST.FOREST.NET"
      DOMAIN: "TESTFOREST"
      ADMINPASS: "SecretC123!"
    ports:
      - "4389:389"
      - "4636:636"
    volumes:
      - ./entrypoint_c.d:/entrypoint.d
      - ./dev-certs:/certs  # <-- Point this to your project subfolder with the certs for DOMAIN_C_SERVER